### ISSUE TITLE
composer versions

### ISSUE THREAD

**Issue by daemon-byte** [nhagemann/anycontent-repository-mysql-php#1]
It seems that this repo requires nhagemann/cmdl-parser-php to be a very old version which conflicts with the version required of nhagemann/anycontent-cms-construction-kit-php 3.3.4. 

That creates the issue:
- Can only install one of: nhagemann/cmdl-parser-php[0.12, 3.0].

Is there any way this can be fixed?

**Comment by nhagemann** [comment]
I'll answer you in an email ...
